---
title: "Leite"
description: ""
author script: 
  - name: "Ítalo Marques-Monteiro"
    github: https://github.com/italomarquesmonteiro
    kaggle: https://www.kaggle.com/talomarquesmonteiro
    linkedin: linkedin.com/in/ítalo-monteiro-0b2516144
    lattes: http://lattes.cnpq.br/7174985368517137
    orcid_id: https://orcid.org/0000-0003-4367-1034
    affiliation: Data Science
date: "2023-08-08"
output: html_document
---

```{r}
library(conflicted)
library(tidyverse)
```


```{r}
leite_temp <- sidrar::get_sidra(api =
    "/t/1086/n3/all/v/282,283/p/all/c12716/allxt/c12529/allxt/d/v282%200,v283%200") |> # nolint: line_length_linter.
    janitor::clean_names("snake") |>
    dplyr::glimpse()
```


```{r}
leite <- leite_temp |>
    dplyr::select(
        valor, unidade_da_federacao_codigo,
            unidade_da_federacao, variavel, trimestre_codigo,
                 trimestre, referencia_temporal, tipo_de_inspecao
    ) |>
    dplyr::relocate(
        unidade_da_federacao_codigo, unidade_da_federacao,
         referencia_temporal, trimestre_codigo, trimestre,
            tipo_de_inspecao, variavel, valor
    ) |>
    dplyr::rename(
        code_state = unidade_da_federacao_codigo,
        name_state = unidade_da_federacao,
        date = trimestre_codigo,
        inspecao = tipo_de_inspecao
    ) |>
    dplyr::mutate(
        code_state = as.double(code_state),
            #date = as.double(date),
                date = lubridate::as_date(date),
                    valor = as.double(valor)
    ) |>
    dplyr::glimpse()
leite |>
    tibble::view()
```

```{r}
x <- lubridate::ymd(199701)
```
