---
title: "Preço do leite"
description: "Dados do CEPEA-Esalq-USP"
author script: 
  - name: "Ítalo Marques-Monteiro"
    github: https://github.com/italomarquesmonteiro
    kaggle: https://www.kaggle.com/talomarquesmonteiro
    linkedin: linkedin.com/in/ítalo-monteiro-0b2516144
    lattes: http://lattes.cnpq.br/7174985368517137
    orcid_id: https://orcid.org/0000-0003-4367-1034
    affiliation: Smart Data  
        
date: "2023-08-14"
output: html_document
---

```{r}
library(conflicted)
library(tidyverse)
```

```{r}
readxl::read_xlsx(
        "C:/Users/italo/OneDrive/Área de Trabalho/VsCode/cepea/PrecoLeite.xlsx") |>
    readr::write_csv("C:/Users/italo/OneDrive/Área de Trabalho/VsCode/cepea/CepeaPrecoLeite.csv")
```

```{r}
setwd("C:/Users/italo/OneDrive/Área de Trabalho/VsCode/cepea/")
```

```{r}
temp <- readr::read_csv("CepeaPrecoLeite.csv",
        skip = 3) |>
    janitor::clean_names("snake") |>
    dplyr::mutate(
        date = case_when(
            mes == "JAN" ~ "01",
            mes == "FEV" ~ "02",
            mes == "MAR" ~ "03",
            mes == "ABR" ~ "04",
            mes == "MAI" ~ "05",
            mes == "JUN" ~ "06",
            mes == "JUL" ~ "07",
            mes == "AGO" ~ "08",
            mes == "SET" ~ "09",
            mes == "OUT" ~ "10",
            mes == "NOV" ~ "11",
            mes == "DEZ" ~ "12",
            TRUE ~ mes
        ),
        date = as.double(date), .before = ano,
        date = lubridate::make_date(ano, date),
        preco_medio = format(round(preco_medio, 2), nsmall = 2),
        preco_medio = as.double(preco_medio), 
        data = lubridate::month(date, label = TRUE)
    ) |>
    dplyr::select(!mes) |>
    dplyr::rename(mes = data) |>
    dplyr::glimpse()
temp |> tibble::view()
```

```{r}
scaleFUN <- function(x) format(round(as.numeric(x), 0), nsmall = 0)

# Create line chart theme
theme_swd_line <-   theme(
  plot.title = element_text(size = rel(1.75), color = "steelblue"), #steelblue
  plot.margin = margin(20, 20, 20, 20),
  text = element_text(family = "Roboto", color = "#979797"),
  axis.title.x = element_text(hjust = 0, vjust = -0.5),
  axis.title.y = element_blank(),
  axis.text.y = element_blank(),
  line = element_blank(),
  rect = element_blank()
)
```


Preço médio do período 
```{r}
temp |>
    dplyr::filter(estado == "BRASIL") |>
    dplyr::arrange(desc(preco_medio)) #|> view()
```


```{r}
preco_leite <- temp |>
    dplyr::filter( estado == "BRASIL") |>
    ggplot2::ggplot(aes(x = date, y = preco_medio, color = estado)) +
                geom_line(color = "steelblue") +
                geom_hline(yintercept = 1.13, lty = 3, color = "gray30") +
                theme_swd_line +
                labs(title = "Preço do leite no Brasil (R$/litro)",
                    subtitle = "# Série histórica
                    by Ítalo Monteiro
                    Source: CEPEA/ESALQ(2023)",
                    x = "Período [mês-ano]") +
                guides(fill = FALSE) +
                scale_x_date(date_labels = "%m/%Y", date_breaks = "6 month") +
                theme(axis.text.x = element_text(angle = 60)) +
                annotate("text", label = "Média do período - R$ 1,13",
                    x = as.Date(
                        "2005-08-01"), y = 1.2, size = 4, colour = "gray60") +
                annotate("text", label = "R$ 3,57 / jul-2022",
                    x = as.Date(
                        "2022-07-01"), y = 3.65, size = 4, colour = "#E46726") +
                annotate("text", label = "R$ 2,56 / jun-2023",
                    x = as.Date(
                        "2023-12-01"), y = 2.54, size = 4, colour = "gray30") +
                annotate("text", label = "R$ 2,90 / abr-2023",
                    x = as.Date(
                        "2023-12-01"), y = 2.95, size = 4, colour = "steelblue")
preco_leite
```

```{r}
ggsave("Images/preco_leite.png",
    plot = preco_leite,
    dpi = 1200,
    width = ,
    height = )
```